#:schema node_modules/wrangler/config-schema.json
name = "spring-frog-3bdf"
main = "src/index.ts"
compatibility_date = "2024-12-18"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "todo-api"
database_id = "1be41cb4-6fc3-44aa-b779-703b7265e367"
